FROM node:16 as build-stage
# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN npm run build

FROM nginx:1.19.1-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

#COPY nginx/nginx.conf /etc/nginx/conf.d/nginx.conf
#COPY nginx/default.conf /etc/nginx/conf.d/default.conf
#
#RUN rm /etc/nginx/conf.d/default.conf
#RUN rm /etc/nginx/conf.d/nginx.conf

EXPOSE 3010
#CMD [ "http-server", "dist", "-p", "3010", "push-state"]
CMD [ "nginx", "-g", "daemon off;" ]